version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
  api:
    build: ../../
    tty: true
    stdin_open: true
    env_file:
      - '.env'
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ../../:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  sidekiq:
    build: ../../
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    volumes:
      - ../../:/myapp
    env_file:
      - '.env'
    depends_on:
      - redis
volumes:
  redis:
  postgres:
