version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=496737041968.dkr.ecr.ap-southeast-1.amazonaws.com/demo-rails-app
      - echo $(aws ecr get-login-password --region ap-southeast-1) | docker login --username AWS --password-stdin $REPOSITORY_URI
      - TIME_STAMP=$( date +%s )
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:v$TIME_STAMP
      - echo Migrate Database...
      - docker run -e RAILS_ENV -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e $REPOSITORY_URI bundle exec rake db:migrate:status
      - docker run -e RAILS_ENV -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e $REPOSITORY_URI bundle exec rake db:migrate
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:v$TIME_STAMP
      - echo Writing image definitions file...
      - printf '[{"name":"video_sharing_api","imageUri":"%s"}]' $REPOSITORY_URI:v$TIME_STAMP > imagedefinitions-rails.json
artifacts:
  files: imagedefinitions-rails.json
