version: '3'
services:
  api:
    build: 
      context: ../../
      dockerfile: docker/development/Dockerfile
    tty: true
    stdin_open: true
    env_file:
      - '.env'
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ../../:/myapp
    ports:
      - "3001:3001"
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  sidekiq:
    build: 
      context: ../../
      dockerfile: docker/production/Dockerfile
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    volumes:
      - ../../:/myapp
    env_file:
      - '.env'
    depends_on:
      - redis
volumes:
  redis:
