default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER_NAME'] || 'admin' %>
  password: <%= ENV['DB_PASSWORD'] || '12345678' %>
  port: <%= ENV['DB_PORT'] || 5432 %> 
  host: <%= ENV['DB_HOST'] || 'localhost' %> 
  reconnect: true

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'video_sharing_development'%>
test:
  <<: *default
  database: video_sharing_test
production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'video_sharing_production'%>
